-- DROP TABLE IF EXISTS department;

CREATE TABLE department
  (
     department_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
     dept_name     VARCHAR(255),
     manager_id    BIGINT NOT NULL,
     PRIMARY KEY (department_id)
  );;
  
--DROP TABLE IF EXISTS employee;

  CREATE TABLE employee
  (
     employee_id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
     email         VARCHAR(255),
     first_name    VARCHAR(255),
     hire_date     TIMESTAMP,
     last_name     VARCHAR(255),
     manager_id    BIGINT,
     phone_number  VARCHAR(255),
     salary        DOUBLE,
     department_id BIGINT,
     PRIMARY KEY (employee_id)
  );
  
ALTER TABLE employee
  ADD CONSTRAINT fkbejtwvg9bxus2mffsm3swj3u9 FOREIGN KEY (department_id)
  REFERENCES department ;